### ISSUE TITLE
Why "cannot import name 'Table' from 'drawbox'"?

### ISSUE THREAD

**Issue by Huaweidev** [reorx/drawtable#3]
My error code:
`>>> from drawbox import Table
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Table' from 'drawbox' (D:\Program Files (x86)\Python\Python37-32\lib\site-packages\drawbox\__init__.py)`

My python environment:
> Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32

**Comment by reorx** [comment]
Sorry for the wrong words, this project was called "drawbox" at the beginning, but was renamed to "drawtable" when released. The "drawbox" you see in README are the vestige I forgot to clean up. Now it is corrected, thanks for reporting :)

Also it seems you have installed the wrong package, to fix this problem, just uninstall `drawbox` and re-install `drawtable`.

```
pip uninstall -y drawbox
pip install -U drawtable
```

**Comment by Huaweidev** [comment]
I have another issue after i execute "pip uninstall -y drawbox" and "pip install -U drawtable":

> D:\Program Files (x86)\Python\Python37-32\Scripts\samples>dir
2019/01/22  21:57 <DIR> .
2019/01/22  21:57 <DIR> ..
2019/01/22  21:50                69 foo.csv
D:\Program Files (x86)\Python\Python37-32\Scripts\samples>csvless foo.csv
Traceback (most recent call last):
  File "d:\program files (x86)\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files (x86)\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\Python\Python37-32\Scripts\csvless.exe\__main__.py", line 9, in <module>
  File "d:\program files (x86)\python\python37-32\lib\site-packages\drawtable\csvless\__main__.py", line 19, in main
    _main()
  File "d:\program files (x86)\python\python37-32\lib\site-packages\drawtable\csvless\__main__.py", line 54, in _main
    p = subprocess.Popen(less_cmd, stdin=subprocess.PIPE)
  File "d:\program files (x86)\python\python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "d:\program files (x86)\python\python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] system can't find the specific file。
